# nixpacks.toml

[phases.setup]
aptPkgs = [
    "ffmpeg",
    "libgl1",            # ✅ required for libGL.so.1
    "libglib2.0-0",
    "libsm6",
    "libxrender1",
    "libxext6",
    "build-essential",
    "python3-opencv"
]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[nixpkgs]
libs = ["libGL", "libX11", "libglvnd"]
packages = ["opencv", "ffmpeg"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --root-path /video-converter"

[variables]
PORT = "8000"