[phases.setup]
aptPkgs = [
  "python3",
  "python3-venv",
  "python3-opencv",
  "ffmpeg",
  "libgl1",
  "libglib2.0-0",
  "libsm6",
  "libxrender1",
  "libxext6",
  "build-essential"
]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[nixpkgs]
libs = ["libGL", "libX11", "libglvnd", "glib"]
packages = ["ffmpeg"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --root-path /video-converter"

[variables]
PORT = "8000"