[phases.setup]
aptPkgs = ["ffmpeg", "python3-opencv", "libgl1-mesa-glx", "libglib2.0-0"]
providers = ["python3", "python3-pip"]

[phases.install]
cmds = ["pip3 install --upgrade pip setuptools wheel", "pip3 install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PORT = "8000"

[nixpacks]
choose-nixpacks = "python"
python-version = "3.10"
plan = "nix"

[nixpkgs]
python310 = true
python310Packages.pip = true
