[phases.setup]
aptPkgs = ["ffmpeg", "python3-opencv", "libgl1-mesa-glx", "libglib2.0-0", "python3-pip"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PORT = "8000"

[nixpacks]
choose-nixpacks = "python"
python-version = "3.12"
