[phases.setup]
aptPkgs = [
    "ffmpeg", 
    "libgl1-mesa-glx", 
    "libglib2.0-0", 
    "libsm6", 
    "libxrender1", 
    "libxext6", 
    "python3-opencv",
    "build-essential"
]

[phases.install]
cmds = ["./setup.sh"]

[nixpkgs]
libs = ["libGL", "libX11", "libglvnd"]
packages = ["opencv", "ffmpeg"]


[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --root-path /video-converter"

[variables]
PORT = "8000"
